import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
import { fetchOneEntry } from "@builder.io/sdk-react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const PUBLIC_API_KEY = process.env.NEXT_PUBLIC_BUILDER_API_KEY;

export default async function RootLayout({ children }) {
  const siteData = await fetchOneEntry({
    apiKey: PUBLIC_API_KEY,
    model: "site-data",
  });

  const bodyFont = siteData?.data?.googleFontbody || "Roboto";
  const displayFont = siteData?.data?.googleFontHeading || "Roboto";
  const siteBackground = siteData?.data?.siteBackground;

  const googleFontsUrl = `https://fonts.googleapis.com/css2?family=${bodyFont.replace(
    " ",
    "+"
  )}&family=${displayFont.replace(" ", "+")}&display=swap`;

  return (
    <html lang="en" data-theme="cupcake" className="min-h-screen">
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM} />
      <body className="min-h-screen flex flex-col justify-center">
        <link rel="stylesheet" href={googleFontsUrl} />
        <style>
          {`
            :root {
              --font-body: '${bodyFont}', sans-serif;
              --font-display: '${displayFont}', sans-serif;
              position: relative;
            }
            ${siteBackground ? `body { background-color: ${siteBackground}; }` : ''}
          `}
        </style>
        {children}
      </body>
    </html>
  );
}
